const constants = {
  CREATE_GAME: 'CREATE_GAME',
  CONNECT_PLAYER: 'CONNECT_PLAYER',
  PLAYER_READY: 'PLAYER_READY',
  START_GAME: 'START_GAME',
  PICK_GESTURE: 'PICK_GESTURE',
  GET_RESULT: 'GET_RESULT',
  ADD_MESSAGE: 'ADD_MESSAGE',
};

export default constants;
